---
- hosts: all
  vars:
    delay_time: 30
  tasks:
    - name: check date
      command: date
      register: out
    - debug: msg={{out.stdout}}
    - pause: seconds={{ delay_time }}
    - name: check date
      command: date
      register: out
    - debug: msg={{out.stdout}}
