---

- name: Hello World!
  hosts: all
  tasks:
  - name: Hello World!
    shell: echo "Hi! Tower is working!"
    shell: echo "Waiting for 30 seconds"
  - pause:
    minutes: 30
    shell: echo "Wait over"
    register: result
- debug:
    var: result
    verbosity: 2
