---

- name: Hello World!
  hosts: all
  tasks:
  - name: Hello World!
    shell: echo "Hi! Tower is working!"
    shell: echo "Waiting for 30 seconds"
  - pause:
    seconds: 30
    shell: echo "Wait over"
