---
- hosts: all
  tasks:
    - name: check date
      command: date
      register: out
    - debug: msg={{out.stdout}}
    - pause: seconds=10
    - name: check date
      command: date
      register: out
    - debug: msg={{out.stdout}}
